version: "1.0"
info:
  model: int-scaffold
packages:
- name: SttDeployEverywhereProject
  gitServerName: sttlab GH
  gitUrl: https://github.com/sttlab-tech
  gitUsername: sttlab-tech
  gitBranch: main
services:
- serviceName: project.sttdeployeverywhere.integrations:sayHello
  packages:
  - name: SttDeployEverywhereProject
    version: "1.0"
